"""Deliberately awkward regeneration of the golden reference file.

Regenerating a golden file is how a behavioural suite quietly stops testing
anything: a decision changes, the test goes red, someone reruns the generator,
and the regression ships with a green tick. This script therefore refuses to
run unless the caller states -- in the shell history, and in the commit that
follows -- that they looked at what changed and why.

    python -m scripts.regenerate_golden --reviewed-by "Name" --reason "..."

It prints a full diff of every decision it is about to change and requires
interactive confirmation. The reviewer and reason are written into the file's
header, so `git blame` on the golden file names a person, not a tool run.
"""

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

from intent_service.adapters.sklearn_model import SklearnIntentModel
from intent_service.domain.entities import CustomerMessage
from intent_service.domain.policy import PolicyThresholds
from intent_service.service.triage import TriageService

ROOT = Path(__file__).resolve().parent.parent
GOLDEN_PATH = ROOT / "tests" / "behavioural" / "golden_decisions.json"
CASES_PATH = ROOT / "tests" / "behavioural" / "golden_cases.json"
MODEL_PATH = ROOT / "models" / "intent_model.joblib"

# Pinned here AND asserted by the test suite. The golden file is only
# meaningful against known thresholds: a recorded "human_review" says nothing
# if the band that produced it could have been anything.
THRESHOLDS = PolicyThresholds(auto_route_floor=0.60, reject_floor=0.25)


def compute() -> dict[str, dict[str, object]]:
    model = SklearnIntentModel.load(MODEL_PATH)
    service = TriageService(model=model, thresholds=THRESHOLDS, cache=None)
    cases: list[str] = json.loads(CASES_PATH.read_text(encoding="utf-8"))
    out: dict[str, dict[str, object]] = {}
    for text in cases:
        decision = service.triage(CustomerMessage(text=text)).decision
        # Confidence is NOT recorded. It is a float that moves with every
        # sklearn patch release; pinning it would make the golden file fail
        # for reasons that have nothing to do with the service's behaviour.
        # The DECISION is what the product promises, so the decision is what
        # is pinned.
        out[text] = {
            "action": decision.action,
            "department": decision.department,
            "priority": decision.priority,
            "intent": decision.intent,
            "urgency_signals": decision.urgency_signals,
        }
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reviewed-by", required=True, help="Who reviewed the diff below")
    parser.add_argument("--reason", required=True, help="Why these decisions should change")
    parser.add_argument("--yes", action="store_true", help="Skip the interactive prompt (CI only)")
    args = parser.parse_args()

    fresh = compute()
    previous: dict[str, dict[str, object]] = {}
    if GOLDEN_PATH.exists():
        previous = json.loads(GOLDEN_PATH.read_text(encoding="utf-8")).get("decisions", {})

    changes = [(k, previous.get(k), v) for k, v in fresh.items() if previous.get(k) != v]
    removed = [k for k in previous if k not in fresh]

    if not changes and not removed:
        print("No decisions changed. Golden file left untouched.")
        return 0

    print(f"\n{len(changes)} changed, {len(removed)} removed:\n")
    for text, old, new in changes:
        print(f"  {text!r}\n    before: {old}\n    after:  {new}\n")
    for text in removed:
        print(f"  REMOVED {text!r}")

    if not args.yes:
        answer = input("\nAccept these changes as the new expected behaviour? [type 'yes'] ")
        if answer.strip().lower() != "yes":
            print("Aborted. Golden file unchanged.")
            return 1

    GOLDEN_PATH.write_text(
        json.dumps(
            {
                "_comment": (
                    "Generated by scripts/regenerate_golden.py. Do NOT regenerate "
                    "to make a failing test pass -- a diff here is a behaviour "
                    "change and belongs in code review."
                ),
                "reviewed_by": args.reviewed_by,
                "reason": args.reason,
                "generated_at": dt.datetime.now(dt.UTC).isoformat(timespec="seconds"),
                "thresholds": THRESHOLDS.model_dump(),
                "decisions": fresh,
            },
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"\nWrote {GOLDEN_PATH} (reviewed by {args.reviewed_by}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
